CREATE TABLE ECAMPAIGN.PA_TMP_PD_EXC_PROMO
(
    ID VARCHAR2(50 CHAR) DEFAULT SYS_GUID() NOT NULL, 
    PAYDISC_CODE VARCHAR2(13 CHAR), 
    PROMOTION_TYPE_CODE VARCHAR2(5 CHAR),
    CREATE_DATE DATE,
    CREATE_BY VARCHAR2(20 CHAR),
    UPDATE_DATE DATE,
    UPDATE_BY VARCHAR2(20 CHAR),
    CONSTRAINT PA_TMP_PD_EXC_PROMO_PK PRIMARY KEY (ID)
);