CREATE TABLE ECAMPAIGN.PA_TMP_PD_EFF_SUPPLIER 
(
    ID VARCHAR2(50 CHAR) DEFAULT SYS_GUID() NOT NULL, 
    PAYDISC_CODE VARCHAR2(13 CHAR), 
    SUPPLIER_CODE VARCHAR2(9 CHAR), 
    CREATE_DATE DATE, 
    CREATE_BY VARCHAR2(20 CHAR), 
    UPDATE_DATE DATE, 
    UPDATE_BY VARCHAR2(20 CHAR), 
    CONSTRAINT PA_TMP_PD_EFF_SUPPLIER_PK PRIMARY KEY (ID)
);