CREATE TABLE ECAMPAIGN.PA_TMP_MP_MASTER (
    ID                 VARCHAR2(50 CHAR) DEFAULT SYS_GUID() NOT NULL,
    MEMPRICE_CODE      VARCHAR2(13 CHAR) NOT NULL,
    MEMPRICE_NAME      VARCHAR2(200 CHAR),
    LIMIT_TYPE         VARCHAR2(3 CHAR),
    LIMIT_VALUE        NUMBER,
    AMOUNT_TYPE        VARCHAR2(4 CHAR),
    AMOUNT_VALUE       NUMBER,
    AMOUNT_CONDITION   VARCHAR2(2 CHAR),
    START_DATE         DATE,
    END_DATE           DATE,
    LIMIT_QTY_RECEIPT  NUMBER,
    LIMIT_QTY_DAYCARD  NUMBER,
    LIMIT_QTY_EVNCARD  NUMBER,
    STATUS             VARCHAR2(2 CHAR),
    CURRENCY           VARCHAR2(10 CHAR),
    COUNTRY            VARCHAR2(10 CHAR),
    CAMPAIGN_ID        VARCHAR2(50 CHAR),
    CREATE_DATE        DATE,
    CREATE_BY          VARCHAR2(20 CHAR),
    UPDATE_DATE        DATE,
    UPDATE_BY          VARCHAR2(20 CHAR)
);

ALTER TABLE ECAMPAIGN.PA_TMP_MP_MASTER
    ADD CONSTRAINT PK_PA_TMP_MP_MASTER
    PRIMARY KEY (ID);

CREATE INDEX ECAMPAIGN.IDX_PA_TMP_MP_MASTER_01
    ON ECAMPAIGN.PA_TMP_MP_MASTER (MEMPRICE_CODE);

CREATE INDEX ECAMPAIGN.IDX_PA_TMP_MP_MASTER_02
    ON ECAMPAIGN.PA_TMP_MP_MASTER (START_DATE, END_DATE);

CREATE INDEX ECAMPAIGN.IDX_PA_TMP_MP_MASTER_03
    ON ECAMPAIGN.PA_TMP_MP_MASTER (STATUS);