CREATE TABLE ECAMPAIGN.PA_TMP_PD_CARD_TYPE 
(
	ID VARCHAR2(50 CHAR) DEFAULT SYS_GUID() NOT NULL, 
	PAYDISC_CODE VARCHAR2(13 CHAR), 
	CARD_TYPE_CODE VARCHAR2(5 CHAR), 
	CARD_TYPE_SCODE VARCHAR2(5 CHAR), 
	CREATE_DATE DATE, 
	CREATE_BY VARCHAR2(20 CHAR), 
	UPDATE_DATE DATE, 
	UPDATE_BY VARCHAR2(20 CHAR), 
	CONSTRAINT PA_TMP_PD_CARD_TYPE_PK PRIMARY KEY (ID)
);