CREATE TABLE ECAMPAIGN.PA_TMP_PD_EXC_SPO
(
    ID VARCHAR2(50 CHAR) DEFAULT SYS_GUID() NOT NULL, 
    PAYDISC_CODE VARCHAR2(13 CHAR), 
    TYPE VARCHAR2(10 CHAR),
    VALUE_TYPE VARCHAR2(10 CHAR),
    CONDITION_VALUE VARCHAR2(10 CHAR),
    CREATE_DATE DATE,
    CREATE_BY VARCHAR2(20 CHAR),
    UPDATE_DATE DATE,
    UPDATE_BY VARCHAR2(20 CHAR),
    CONSTRAINT PA_TMP_PD_EXC_SPO_PK PRIMARY KEY (ID)
);