CREATE TABLE ECAMPAIGN.PA_TMP_PD_EFF_ARTICLE
(
    ID VARCHAR2(50 CHAR) DEFAULT SYS_GUID() NOT NULL, 
    PAYDISC_CODE VARCHAR2(13 CHAR), 
    ARTICLE_CODE VARCHAR2(14 CHAR), 
    BARCODE VARCHAR2(14 CHAR), 
    CREATE_DATE DATE, 
    CREATE_BY VARCHAR2(20 CHAR), 
    UPDATE_DATE DATE, 
    UPDATE_BY VARCHAR2(20 CHAR), 
    CONSTRAINT PA_TMP_PD_EFF_ARTICLE_PK PRIMARY KEY (ID)
);