TRUNCATE TABLE ECAMPAIGN.PA_TMP_PD_EXC_PROMO;

INSERT INTO ECAMPAIGN.PA_TMP_PD_EXC_PROMO (
    PAYDISC_CODE, 
    PROMOTION_TYPE_CODE, 
    CREATE_DATE, 
    CREATE_BY, 
    UPDATE_DATE, 
    UPDATE_BY
) 
SELECT DISTINCT 
    MAS.PAYDISC_CODE AS PAYDISC_CODE,
    CASE EXP.PROMOTION_TYPE_CODE
        WHEN '100' THEN 'PCPN'
        WHEN '200' THEN 'MM'
        WHEN '300' THEN 'MP'
        WHEN '400' THEN 'PD'
        WHEN '600' THEN 'TC'
        ELSE null
    END AS PROMOTION_TYPE_CODE,
   :pCreateDate AS CREATE_DATE,
   :pCreateBy   AS CREATE_BY,
   :pCreateDate AS UPDATE_DATE,
   :pCreateBy   AS UPDATE_BY
FROM ECAMPAIGN.PA_TMP_PD_MASTER MAS 
JOIN ECAMPAIGN.EXCEPTION_PROMOTION EXP
ON MAS.PAYDISC_CODE = EXP.RULE_ID;