TRUNCATE TABLE ECAMPAIGN.PA_TMP_PD_EXC_SPO;

INSERT INTO ECAMPAIGN.PA_TMP_PD_EXC_SPO (
    PAYDISC_CODE, 
    TYPE, 
    VALUE_TYPE, 
    CONDITION_VALUE, 
    CREATE_DATE, 
    CREATE_BY, 
    UPDATE_DATE, 
    UPDATE_BY
) 
SELECT DISTINCT 
    MAS.PAYDISC_CODE AS PAYDISC_CODE,
    EXSPO.TYPE AS TYPE,
    EXSPO.VALUE_TYPE AS VALUE_TYPE,
    EXSPO.CONDITION_VALUE AS CONDITION_VALUE,
   :pCreateDate AS CREATE_DATE,
   :pCreateBy   AS CREATE_BY,
   :pCreateDate AS UPDATE_DATE,
   :pCreateBy   AS UPDATE_BY
FROM ECAMPAIGN.PA_TMP_PD_MASTER MAS 
JOIN ECAMPAIGN.PAYDISCEXCSPO EXSPO
ON MAS.PAYDISC_CODE = EXSPO.RULE_ID;