TRUNCATE TABLE ECAMPAIGN.PA_TMP_PD_CARD_TYPE;

INSERT INTO ECAMPAIGN.PA_TMP_PD_CARD_TYPE (
    PAYDISC_CODE, 
    CARD_TYPE_CODE, 
    CARD_TYPE_SCODE, 
    CREATE_DATE, 
    CREATE_BY, 
    UPDATE_DATE, 
    UPDATE_BY
)
SELECT DISTINCT
    MAS.PAYDISC_CODE  AS PAYDISC_CODE, 
    ECT.CARD_CODE     AS CARD_TYPE_CODE, 
    ECT.CARD_SUB_CODE AS CARD_TYPE_SCODE, 
    :pCreateDate      AS CREATE_DATE,
    :pCreateBy        AS CREATE_BY,
    :pCreateDate      AS UPDATE_DATE,
    :pCreateBy        AS UPDATE_BY
FROM PA_TMP_PD_MASTER MAS
JOIN EFFECT_CARDTYPE ECT
    ON MAS.PAYDISC_CODE = ECT.RULE_ID;