TRUNCATE TABLE ECAMPAIGN.PA_TMP_PD_EFF_SUPPLIER;

INSERT INTO ECAMPAIGN.PA_TMP_PD_EFF_SUPPLIER (
    PAYDISC_CODE, 
    SUPPLIER_CODE, 
    CREATE_DATE, 
    CREATE_BY, 
    UPDATE_DATE, 
    UPDATE_BY
)
SELECT DISTINCT 
    MAS.PAYDISC_CODE AS PAYDISC_CODE,
    EFS.SUPPLIER_CODE AS SUPPLIER_CODE,
   :pCreateDate AS CREATE_DATE,
   :pCreateBy   AS CREATE_BY,
   :pCreateDate AS UPDATE_DATE,
   :pCreateBy   AS UPDATE_BY
FROM ECAMPAIGN.PA_TMP_PD_MASTER MAS
JOIN ECAMPAIGN.EFFECT_SUPPLIER EFS
ON MAS.PAYDISC_CODE = EFS.RULE_ID
WHERE NOT EXISTS (
    SELECT 1
    FROM EXCEPTION_SUPPLIER EXS
    WHERE MAS.PAYDISC_CODE = EXS.RULE_ID
    AND EFS.SUPPLIER_CODE = EXS.SUPPLIER_CODE
);