INSERT INTO ECAMPAIGN.PA_TMP_MP_EXC_BRAND (
    MEMPRICE_CODE, 
    BRAND_CODE, 
    CREATE_DATE, 
    CREATE_BY, 
    UPDATE_DATE, 
    UPDATE_BY
) 
SELECT DISTINCT 
    MAS.MEMPRICE_CODE AS MEMPRICE_CODE,
    EXB.BRAND_CODE AS BRAND_CODE,
   :pCreateDate AS CREATE_DATE,
   :pCreateBy   AS CREATE_BY,
   :pCreateDate AS UPDATE_DATE,
   :pCreateBy   AS UPDATE_BY
FROM ECAMPAIGN.PA_TMP_MP_MASTER MAS 
JOIN ECAMPAIGN.EXCEPTION_BRAND EXB
ON MAS.MEMPRICE_CODE = EXB.RULE_ID;


