TRUNCATE TABLE ECAMPAIGN.PA_TMP_PD_EXC_BRAND;

INSERT INTO ECAMPAIGN.PA_TMP_PD_EXC_BRAND (
    PAYDISC_CODE, 
    BRAND_CODE, 
    CREATE_DATE, 
    CREATE_BY, 
    UPDATE_DATE, 
    UPDATE_BY
) 
SELECT DISTINCT 
    MAS.PAYDISC_CODE AS PAYDISC_CODE,
    EXB.BRAND_CODE AS BRAND_CODE,
   :pCreateDate AS CREATE_DATE,
   :pCreateBy   AS CREATE_BY,
   :pCreateDate AS UPDATE_DATE,
   :pCreateBy   AS UPDATE_BY
FROM ECAMPAIGN.PA_TMP_PD_MASTER MAS 
JOIN ECAMPAIGN.EXCEPTION_BRAND EXB
ON MAS.PAYDISC_CODE = EXB.RULE_ID;


